##
# B-tree Data Structure
#
# @file
# @version 0.1

CC = g++
SOURCE = test.cpp
OUTPUT = btree.out

build:
	${CC} ${SOURCE} -g -o ${OUTPUT}

clean:
	rm -f *.o *.out

run:
	./${OUTPUT} 100

all: clean build run

# end
